### ISSUE TITLE
Unable to resolve action reclaim-the-stack/rubocop-action@v1

### ISSUE THREAD

**Issue by falegk** [reclaim-the-stack/rubocop-action#5]
Hi,

looks like github cannot find the action
`Unable to resolve action reclaim-the-stack/rubocop-action@v1, unable to find version v1`

here is my action
```
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true
      - name: Rubocop
        uses: reclaim-the-stack/rubocop-action@v1
        with:
          rubocop_version: Gemfile # get rubocop version from Gemfile.lock
          rubocop_arguments: --config .rubocop.yml
```
